export { default as Logo } from './Logo.svg'
export { default as FrameMobR } from "./FrameMobR.svg";
export { default as FrameMobL } from "./FrameMobL.svg";
export { default as FrameTabR } from "./FrameTabR.svg";
export { default as FrameTabL } from "./FrameTabL.svg";
export { default as FrameDeskR } from "./FrameDeskR.svg";
export { default as FrameDeskL } from "./FrameDeskL.svg";
export { default as Error } from "./Error.svg";
export { default as Active } from "./Active.svg";